services:
  app:
    build: .
    ports:
      - "8081:8081"
    environment:
      - EXPO_NO_TELEMETRY=1
      - REACT_NATIVE_PACKAGER_HOSTNAME=${REACT_NATIVE_PACKAGER_HOSTNAME:-192.168.0.100}
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
      - /app/node_modules
